### ISSUE TITLE
Borrar componentes repetitivos y crear uno solo

### ISSUE THREAD

**Issue by CambaSoft-dev** [CambaSoft/WebPage-Angular#24]
Solo borrar componentes repetidos, no aumentar IFs

**Comment by JrogeT** [comment]
Para las imágenes, puedes crearte otro input en el componente:
`Input() imageUrl: string;`

Así le pasas la url por parámetro desde el html (como title y servicios)

`<img src="{{ imageUrl }}" width="100%">`
